"""File containing the function to optimize.

The objective has been moved into its own file to be sent to a remote worker.

Functions
---------
objective
    The objective function to optimize.
"""

import math


def objective(params):
    """The objective function to optimize.

    Parameters
    ----------
    params : dict
        Dictionary of parameters generated by SHADHO.
    
    Returns
    -------
    float
        The value to optimize over.
    """
    x = params['x']
    y = params['y']

    return math.sin(x) * math.cos(y)


if __name__ == '__main__':
    # The SHADHO worker is a wrapper that unpacks hyperparameters sent by the
    # driver, passes them into the objective, retrieves the result, and
    # packages the result to return to the driver.
    import shadho_worker
    shadho_worker.run(objective)